In [1]:
import numpy as np 
from scipy.io import loadmat
import pandas as pd

/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)


In [2]:
features=loadmat("example.mat")

#查看有返回的类型和他的键
print("keys:",features.keys())
#分离querys和features
features = np.asarray(features['our_feature1'])
querys=features[features[:,-1]%100==0]
features,features_number = features[:,:-1],features[:,-1] 
querys,querys_number = querys[:,:-1],querys[:,-1] 
print(querys.shape)

#得到一范数度量
result=np.sum(np.abs(features-querys[:,np.newaxis,:]),axis=2)
# result=np.power(np.sum(np.power(features-querys[:,np.newaxis,:],2),axis=2),0.5)
print(result.shape)
rank_ID = np.argsort(result,axis=1)
print(rank_ID.shape)
print(rank_ID)

with open("result.dat",'w') as output:
    for i,query_num in enumerate(querys_number):
        pic_suffix = ".jpg"
        query_name = "%6d%s"%(query_num,pic_suffix)
        line=[query_name]
#         for rank,img_name in enumerate(features_number[rank_ID[i,1:21]]):
#             line.append("%d %6d%s"%(rank,img_name,pic_suffix))
        for rank,img_name in enumerate(features_number[rank_ID[i,1:]]):
            if(img_name//100 == query_num //100):
                line.append("%d %6d%s"%(rank,img_name,pic_suffix))       
        output.write(' '.join(line) + '\n')

keys: dict_keys(['__version__', 'our_feature1', '__header__', '__globals__'])
(500, 128)
(500, 1491)
(500, 1491)
[[   0    1   13 ...   49  916  200]
 [   3    5   10 ...   49  916  200]
 [   5   10    0 ...  916   49  200]
 ...
 [1484 1485  706 ...   53  200   49]
 [1486 1487 1191 ...  916   49  200]
 [1488 1356  973 ...  270  231  895]]
